max_retries = 3  # Number of retry attempts
transfermarkt_name_map = {
    "Bosnia and Herzegovina": "Bosnia-Herzegovina",
    "Turkey": "Turkiye",
    "China PR": "China",
    "DR Congo": "Congo DR"
}
transfermarkt_skip = [
    "Jersey",
    "Alderney",
    "Aymara",
    "Biafra",
    "Brunei",
    "Chameria",
    "Elba Island",
    "Falkland Islands",
    "Frøya",
    "Gozo",
    "Greenland",
    "Guernsey",
    "Hitra",
    "Hmong",
    "Isle of Man",
    "Isle of Wight",
    "Kernow",
    "Mapuche",
    "Matabeleland",
    "Maule Sur",
    "Menorca",
    "Northern Mariana Islands",
    "Orkney",
    "Raetia",
    "Réunion",
    "Saint Barthélemy",
    "Saint Helena",
    "Saint Martin",
    "Shetland",
    "Székely Land",
    "Sápmi",
    "Taiwan",
    "Tamil Eelam",
    "Tibet",
    "Ticino",
    "Tuvalu",
    "Two Sicilies",
    "West Papua",
    "Western Isles",
    "Ynys Môn",
    "Yoruba Nation",
    "Zanzibar",
    "Åland Islands"
]